import type { BlockType, BlockConfig } from './types'

export interface BlockDefinition {
  type: BlockType
  label: string
  icon: string
  defaultWidth: number
  defaultHeight: number
  minWidth: number
  minHeight: number
  maxWidth?: number
  maxHeight?: number
  defaultConfig: BlockConfig
  /**
   * Standard settings that apply to this block type.
   * Used to determine which settings should be auto-applied on block creation.
   */
  applicableSettings?: {
    fields?: boolean
    filters?: boolean
    sorts?: boolean
    grouping?: boolean
    appearance?: boolean
    permissions?: boolean
    conditionalFormatting?: boolean
  }
  /**
   * Settings that this block type cannot use.
   * Used to prevent invalid configurations.
   */
  excludedSettings?: string[]
  /**
   * Block can be the single full-page block on a content page.
   * When true, user can set "Full-page mode" and page renders without grid.
   */
  supportsFullPage?: boolean
  /**
   * When adding this block type (e.g. on empty page), suggest full-page by default.
   * Only applies when supportsFullPage is true.
   */
  defaultFullPage?: boolean
  /**
   * When in full-page mode, how this block uses width.
   * - 'fill': block fills the viewport (grid, list, calendar, kanban).
   * - 'rail': fixed-width left rail; does not stretch (e.g. record selector).
   * Omit or undefined = 'fill'.
   */
  fullPageLayout?: 'fill' | 'rail'
  /** When fullPageLayout === 'rail', max width in px. Ignored for 'fill'. */
  fullPageMaxWidth?: number
  /**
   * When in rail full-page mode, this block can show a right-hand record preview driven by page record context.
   * Only controller blocks should set this.
   */
  supportsRecordPreview?: boolean
  /** When true and supportsRecordPreview, show preview by default when context is set. */
  defaultRecordPreview?: boolean
}

export const BLOCK_REGISTRY: Record<BlockType, BlockDefinition> = {
  grid: {
    type: 'grid',
    label: 'Grid',
    icon: 'Grid',
    defaultWidth: 12,
    defaultHeight: 8,
    minWidth: 4,
    minHeight: 4,
    defaultConfig: {
      title: 'Table View',
      table_id: '',
      display_mode: 'fit',
      record_limit: 20,
      overflow_behaviour: 'view_all',
    },
    supportsFullPage: true,
    defaultFullPage: false,
  },
  form: {
    type: 'form',
    label: 'Form',
    icon: 'FileText',
    defaultWidth: 6,
    defaultHeight: 10,
    minWidth: 4,
    minHeight: 6,
    defaultConfig: {
      title: 'Form',
      table_id: '',
    },
  },
  record: {
    type: 'record',
    label: 'Record',
    icon: 'FileText',
    defaultWidth: 6,
    defaultHeight: 8,
    minWidth: 4,
    minHeight: 4,
    defaultConfig: {
      title: 'Record',
      table_id: '',
      record_id: '',
    },
  },
  chart: {
    type: 'chart',
    label: 'Chart',
    icon: 'BarChart',
    defaultWidth: 6,
    defaultHeight: 6,
    minWidth: 4,
    minHeight: 4,
    defaultConfig: {
      title: 'Chart',
      table_id: '',
      chart_type: 'bar',
    },
  },
  kpi: {
    type: 'kpi',
    label: 'KPI',
    icon: 'TrendingUp',
    defaultWidth: 3,
    defaultHeight: 3,
    minWidth: 2,
    minHeight: 2,
    maxWidth: 6,
    maxHeight: 4,
    defaultConfig: {
      title: 'KPI',
      table_id: '',
      kpi_aggregate: 'count',
    },
  },
  kpi_summary: {
    type: 'kpi_summary',
    label: 'KPI Summary',
    icon: 'LayoutGrid',
    defaultWidth: 12,
    defaultHeight: 3,
    minWidth: 6,
    minHeight: 2,
    maxWidth: 12,
    maxHeight: 4,
    defaultConfig: {
      title: 'Marketing Hub KPIs',
    },
    applicableSettings: {
      fields: false,
      filters: false,
      sorts: false,
      grouping: false,
      appearance: true,
      permissions: false,
      conditionalFormatting: false,
    },
  },
  html: {
    type: 'html',
    label: 'HTML',
    icon: 'Code',
    defaultWidth: 6,
    defaultHeight: 4,
    minWidth: 2,
    minHeight: 2,
    defaultConfig: {
      title: 'HTML',
      html: '',
    },
    applicableSettings: {
      fields: false,
      filters: false,
      sorts: false,
      grouping: false,
      appearance: true,
      permissions: false,
      conditionalFormatting: false,
    },
  },
  drive_gallery: {
    type: 'drive_gallery',
    label: 'Google Drive Gallery',
    icon: 'HardDrive',
    defaultWidth: 8,
    defaultHeight: 8,
    minWidth: 4,
    minHeight: 4,
    defaultConfig: {
      title: 'Shared Image Gallery',
      subtitle: 'Approved marine photography by vessel type and sector.',
      drive_folder_id: '',
    },
    applicableSettings: {
      fields: false,
      filters: false,
      sorts: false,
      grouping: false,
      appearance: true,
      permissions: false,
      conditionalFormatting: false,
    },
  },
  text: {
    type: 'text',
    label: 'Text',
    icon: 'Type',
    defaultWidth: 6,
    defaultHeight: 4,
    minWidth: 2,
    minHeight: 2,
    defaultConfig: {
      // Text blocks shouldn't show a generic header by default.
      // (If users want a heading, they can add it as content, or set appearance.title explicitly.)
      title: '',
      text_content: '',
      // Note: 'content' is also supported for backward compatibility
      content: '',
    },
    applicableSettings: {
      fields: false,
      filters: false,
      sorts: false,
      grouping: false,
      appearance: true,
      permissions: false,
      conditionalFormatting: false,
    },
  },
  image: {
    type: 'image',
    label: 'Image',
    icon: 'Image',
    defaultWidth: 4,
    defaultHeight: 4,
    minWidth: 2,
    minHeight: 2,
    defaultConfig: {
      title: 'Image',
      image_url: '',
      image_alt: '',
    },
  },
  gallery: {
    type: 'gallery',
    label: 'Gallery',
    icon: 'Images',
    defaultWidth: 12,
    defaultHeight: 8,
    minWidth: 4,
    minHeight: 4,
    defaultConfig: {
      title: 'Gallery',
      table_id: '',
      view_type: 'gallery',
      display_mode: 'fit',
      record_limit: 12,
      overflow_behaviour: 'view_all',
      card_image_display: 'show_if_available',
      card_show_labels: false,
      card_show_empty_fields: false,
      card_text_behaviour: 'wrap',
      card_height_mode: 'fit',
    },
  },
  divider: {
    type: 'divider',
    label: 'Divider',
    icon: 'Minus',
    defaultWidth: 12,
    defaultHeight: 2, // Default to 2 units for spacing
    minWidth: 2,
    minHeight: 1,
    maxHeight: 20, // Allow larger heights for intentional spacing
    defaultConfig: {
      title: '',
      appearance: {
        divider_height: 2, // Default height setting
      },
    },
  },
  button: {
    type: 'button',
    label: 'Button',
    icon: 'Zap',
    defaultWidth: 3,
    defaultHeight: 2,
    minWidth: 2,
    minHeight: 2,
    maxWidth: 6,
    maxHeight: 3,
    defaultConfig: {
      title: 'Button',
      button_label: 'Click Me',
      button_automation_id: '',
    },
  },
  action: {
    type: 'action',
    label: 'Action',
    icon: 'Zap',
    defaultWidth: 3,
    defaultHeight: 2,
    minWidth: 2,
    minHeight: 2,
    maxWidth: 6,
    maxHeight: 3,
    defaultConfig: {
      title: 'Action',
      action_type: 'navigate',
      label: 'Click Me',
      route: '',
    },
  },
  link_preview: {
    type: 'link_preview',
    label: 'Link Preview',
    icon: 'ExternalLink',
    defaultWidth: 4,
    defaultHeight: 4,
    minWidth: 2,
    minHeight: 2,
    defaultConfig: {
      title: 'Link Preview',
      url: '',
      // Note: 'link_url' is also supported for backward compatibility
      link_url: '',
    },
    applicableSettings: {
      fields: false,
      filters: false,
      sorts: false,
      grouping: false,
      appearance: true,
      permissions: false,
      conditionalFormatting: false,
    },
  },
  filter: {
    type: 'filter',
    label: 'Filter',
    icon: 'Filter',
    defaultWidth: 12,
    defaultHeight: 4,
    minWidth: 4,
    minHeight: 3,
    maxHeight: 8,
    defaultConfig: {
      title: 'Filters',
      table_id: '',
      target_blocks: 'all',
      allowed_fields: [],
      allowed_operators: [],
      filters: [],
    },
  },
  field: {
    type: 'field',
    label: 'Field',
    icon: 'FileText',
    defaultWidth: 6,
    defaultHeight: 3,
    minWidth: 2,
    minHeight: 2,
    defaultConfig: {
      // Field blocks show the field label/value; they shouldn't render a generic header by default.
      // If users want a header, they can set appearance.title explicitly.
      title: '',
      field_id: '',
    },
  },
  field_section: {
    type: 'field_section',
    label: 'Field Section',
    icon: 'FileText',
    defaultWidth: 6,
    defaultHeight: 6,
    minWidth: 4,
    minHeight: 4,
    defaultConfig: {
      title: '',
      group_name: '',
    },
  },
  calendar: {
    type: 'calendar',
    label: 'Calendar',
    icon: 'Calendar',
    defaultWidth: 12,
    defaultHeight: 10,
    minWidth: 6,
    minHeight: 8,
    defaultConfig: {
      title: 'Calendar',
      table_id: '',
      view_type: 'calendar',
      display_mode: 'fit',
      record_limit: 20,
      overflow_behaviour: 'view_all',
    },
    supportsFullPage: true,
    defaultFullPage: false,
  },
  multi_calendar: {
    type: 'multi_calendar',
    label: 'Multi Calendar',
    icon: 'Calendar',
    defaultWidth: 12,
    defaultHeight: 10,
    minWidth: 6,
    minHeight: 8,
    defaultConfig: {
      title: 'Multi Calendar',
      sources: [],
    },
  },
  kanban: {
    type: 'kanban',
    label: 'Kanban',
    icon: 'Columns',
    defaultWidth: 12,
    defaultHeight: 8,
    minWidth: 6,
    minHeight: 6,
    defaultConfig: {
      title: 'Kanban Board',
      table_id: '',
      view_type: 'kanban',
      display_mode: 'fit',
      record_limit: 20,
      overflow_behaviour: 'view_all',
      card_image_display: 'show_if_available',
      card_show_labels: false,
      card_show_empty_fields: false,
      card_text_behaviour: 'wrap',
      card_height_mode: 'fit',
    },
    supportsFullPage: true,
    defaultFullPage: false,
  },
  timeline: {
    type: 'timeline',
    label: 'Timeline',
    icon: 'GitBranch',
    defaultWidth: 12,
    defaultHeight: 8,
    minWidth: 6,
    minHeight: 6,
    defaultConfig: {
      title: 'Timeline',
      table_id: '',
      view_type: 'timeline',
      display_mode: 'fit',
      record_limit: 20,
      overflow_behaviour: 'view_all',
    },
    supportsFullPage: true,
    defaultFullPage: false,
  },
  multi_timeline: {
    type: 'multi_timeline',
    label: 'Multi Timeline',
    icon: 'GitBranch',
    defaultWidth: 12,
    defaultHeight: 8,
    minWidth: 6,
    minHeight: 6,
    defaultConfig: {
      title: 'Multi Timeline',
      sources: [],
    },
  },
  list: {
    type: 'list',
    label: 'List',
    icon: 'List',
    defaultWidth: 12,
    defaultHeight: 8,
    minWidth: 6,
    minHeight: 6,
    defaultConfig: {
      title: 'List View',
      table_id: '',
      view_type: 'list', // List view type
      display_mode: 'fit',
      record_limit: 20,
      overflow_behaviour: 'view_all',
      card_image_display: 'show_if_available',
      card_show_labels: false,
      card_show_empty_fields: false,
      card_text_behaviour: 'wrap',
      card_height_mode: 'fit',
    },
    supportsFullPage: true,
    defaultFullPage: false,
    applicableSettings: {
      fields: true,
      filters: true,
      sorts: true,
      grouping: true,
      appearance: true,
      permissions: true,
      conditionalFormatting: false,
    },
  },
  horizontal_grouped: {
    type: 'horizontal_grouped',
    label: 'Tabs',
    icon: 'LayoutGrid',
    defaultWidth: 12,
    defaultHeight: 8,
    minWidth: 6,
    minHeight: 6,
    defaultConfig: {
      title: 'Tabs View',
      table_id: '',
      group_by_field: '',
    },
  },
  number: {
    type: 'number',
    label: 'Number',
    icon: 'Hash',
    defaultWidth: 4,
    defaultHeight: 3,
    minWidth: 2,
    minHeight: 2,
    maxWidth: 6,
    maxHeight: 4,
    defaultConfig: {
      title: 'Number',
      table_id: '',
      field_id: '',
    },
  },
  content_timeline: {
    type: 'content_timeline',
    label: 'Content Timeline',
    icon: 'GanttChart',
    defaultWidth: 12,
    defaultHeight: 10,
    minWidth: 6,
    minHeight: 8,
    defaultConfig: {
      title: 'Content Timeline',
      table_id: '',
      content_timeline_subtitle:
        'Plan campaigns, posts, pages and marketing activity by theme.',
      content_timeline_default_view: 'quarter',
      content_timeline_group_by: 'theme',
      content_timeline_show_filters: true,
      content_timeline_show_status_badges: true,
      content_timeline_show_owner_initials: true,
      content_timeline_enable_detail_panel: true,
      content_timeline_compact_mode: false,
      is_full_page: false,
      appearance: { showTitle: false },
    },
    applicableSettings: {
      fields: false,
      filters: false,
      sorts: false,
      grouping: false,
      appearance: true,
      permissions: false,
      conditionalFormatting: false,
    },
    supportsFullPage: true,
    defaultFullPage: false,
  },
  event_calendar: {
    type: 'event_calendar',
    label: 'Event Calendar',
    icon: 'CalendarDays',
    defaultWidth: 12,
    defaultHeight: 14,
    minWidth: 8,
    minHeight: 10,
    defaultConfig: {
      title: 'Event Calendar',
      table_id: '',
      event_calendar_subtitle:
        'Discover events, manage attendance and sync to your calendar.',
      event_calendar_default_view: 'month',
      event_calendar_mobile_default_view: 'list',
      event_calendar_detail_mode: 'drawer',
      event_calendar_click_action: 'open_detail',
      event_calendar_allow_attendance_updates: true,
      event_calendar_allow_member_submissions: false,
      event_calendar_allow_calendar_export: true,
      event_calendar_external_mode: false,
      event_calendar_show_toolbar: true,
      event_calendar_show_stats: true,
      event_calendar_show_metrics: true,
      event_calendar_show_filters: true,
      event_calendar_show_search: true,
      event_calendar_show_actions: true,
      event_calendar_show_add_button: true,
      event_calendar_show_attendance_controls: true,
      event_calendar_show_schedule: true,
      event_calendar_show_resources: true,
      event_calendar_show_notes: true,
      event_calendar_show_legend: true,
      event_calendar_show_sync_banner: false,
      event_calendar_feed_scope: 'all',
      event_calendar_submitted_status_value: 'Submitted',
      event_calendar_approved_status_value: 'Published',
      event_calendar_rejected_status_value: 'Cancelled',
      event_calendar_member_default_visibility: 'members_only',
      event_calendar_content_type_default: 'Event',
      event_calendar_density: 'comfortable',
      is_full_page: false,
      appearance: { showTitle: true },
    },
    applicableSettings: {
      fields: false,
      filters: false,
      sorts: false,
      grouping: false,
      appearance: true,
      permissions: false,
      conditionalFormatting: false,
    },
    supportsFullPage: true,
    defaultFullPage: false,
  },
  social_media_calendar: {
    type: 'social_media_calendar',
    label: 'Social Media Calendar',
    icon: 'Share2',
    defaultWidth: 12,
    defaultHeight: 14,
    minWidth: 8,
    minHeight: 10,
    defaultConfig: {
      title: 'Social Media Calendar',
      table_id: '',
      social_media_calendar_subtitle:
        'Visual planning for social posts — platforms, media, and approval status at a glance.',
      social_media_calendar_default_view: 'month',
      social_media_calendar_content_scope: 'social_only',
      social_media_calendar_content_type_default: 'Social Media',
      social_media_calendar_mode: 'full',
      social_media_calendar_show_status_bar: true,
      social_media_calendar_show_filters: true,
      social_media_calendar_show_toolbar: true,
      social_media_calendar_show_media_preview: true,
      social_media_calendar_show_approval_status: true,
      social_media_calendar_show_platform_icons: true,
      is_full_page: false,
      appearance: { showTitle: true },
    },
    applicableSettings: {
      fields: false,
      filters: false,
      sorts: false,
      grouping: false,
      appearance: true,
      permissions: false,
      conditionalFormatting: false,
    },
    supportsFullPage: true,
    defaultFullPage: false,
  },
  campaigns_overview: {
    type: 'campaigns_overview',
    label: 'Campaigns Overview',
    icon: 'LayoutGrid',
    defaultWidth: 12,
    defaultHeight: 12,
    minWidth: 8,
    minHeight: 8,
    defaultConfig: {
      title: 'Campaigns',
      subtitle: 'Plan, manage and track all marketing campaigns.',
      table_id: '',
      campaigns_overview_use_mock: false,
      campaigns_use_mock: false,
      campaigns_default_view: 'list',
      campaigns_group_by: 'status',
      campaigns_show_search: true,
      campaigns_show_filters: true,
      campaigns_show_kpis: true,
      campaigns_show_progress: true,
      campaigns_show_thumbnails: true,
      campaigns_density: 'comfortable',
      campaigns_max_items: 100,
      campaigns_click_action: 'open_record',
      is_full_page: false,
      appearance: { showTitle: false },
    },
    applicableSettings: {
      fields: false,
      filters: false,
      sorts: false,
      grouping: false,
      appearance: true,
      permissions: false,
      conditionalFormatting: false,
    },
    supportsFullPage: true,
    defaultFullPage: false,
  },
  upcoming_summary: {
    type: 'upcoming_summary',
    label: 'Upcoming Summary',
    icon: 'CalendarClock',
    defaultWidth: 12,
    defaultHeight: 10,
    minWidth: 6,
    minHeight: 6,
    defaultConfig: {
      title: 'Upcoming Summary',
      table_id: '',
      upcoming_summary_subtitle:
        'A quick view of deadlines, campaigns and marketing activity needing attention.',
      upcoming_summary_sections: [
        'deadlines',
        'campaigns',
        'events',
        'approval',
        'blockers',
        'published',
      ],
      upcoming_summary_max_items: 5,
      upcoming_summary_layout: 'two_column',
      upcoming_summary_date_range: 'next_30_days',
      upcoming_summary_show_counts: true,
      upcoming_summary_show_dates: true,
      upcoming_summary_show_owners: true,
      upcoming_summary_show_view_all: true,
      upcoming_summary_group_campaigns_by_status: false,
    },
    applicableSettings: {
      fields: false,
      filters: false,
      sorts: false,
      grouping: false,
      appearance: true,
      permissions: false,
      conditionalFormatting: false,
    },
  },
  things_to_do: {
    type: 'things_to_do',
    label: 'Things To Do',
    icon: 'CheckSquare',
    defaultWidth: 12,
    defaultHeight: 10,
    minWidth: 6,
    minHeight: 8,
    defaultConfig: {
      title: 'Things To Do',
      table_id: '',
      things_to_do_subtitle:
        'Tasks, reviews, approvals and actions in one place.',
      things_to_do_default_view: 'list',
      things_to_do_default_grouping: 'due-date',
      things_to_do_show_filters: true,
      things_to_do_show_quick_links: true,
      things_to_do_show_stats: true,
      things_to_do_enable_detail_panel: true,
      things_to_do_date_range: 'next_30_days',
      things_to_do_compact_mode: false,
      is_full_page: false,
      appearance: { showTitle: false },
    },
    applicableSettings: {
      fields: false,
      filters: false,
      sorts: false,
      grouping: false,
      appearance: true,
      permissions: false,
      conditionalFormatting: false,
    },
    supportsFullPage: true,
    defaultFullPage: false,
  },
  content_theme: {
    type: 'content_theme',
    label: 'Content Theme Block',
    icon: 'Lightbulb',
    defaultWidth: 12,
    defaultHeight: 10,
    minWidth: 6,
    minHeight: 6,
    defaultConfig: {
      title: 'Content Themes',
      table_id: '',
      content_theme_subtitle:
        'Strategic themes and content focus areas for the quarter.',
      content_theme_year: 2026,
      content_theme_quarter: 'Q2',
      content_theme_show_filters: true,
      content_theme_show_view_toggle: true,
      content_theme_show_footer: true,
      content_theme_card_density: 'comfortable',
      content_theme_highlight_current_quarter: true,
      content_theme_max_themes: 4,
      content_theme_view_mode: 'grid',
    },
    applicableSettings: {
      fields: false,
      filters: false,
      sorts: false,
      grouping: false,
      appearance: true,
      permissions: false,
      conditionalFormatting: false,
    },
  },
  members_welcome: {
    type: 'members_welcome',
    label: 'Members Welcome',
    icon: 'Home',
    defaultWidth: 12,
    defaultHeight: 22,
    minWidth: 8,
    minHeight: 12,
    defaultConfig: {
      title: 'Welcome to the Peters & May Marketing Hub',
      subtitle:
        'Your events, resources and collaboration tools — all in one place.',
      members_welcome_body:
        'View upcoming activity and update your attendance under Events. Find approved logos, documents and media in the Resource Hub. Got an event to suggest or need a hand? Get in touch with the team.',
      members_welcome_show_quick_actions: true,
      members_welcome_max_events: 5,
      members_welcome_max_resources: 5,
      members_welcome_allow_submit_event: true,
      appearance: { showTitle: false },
    },
    applicableSettings: {
      fields: false,
      filters: false,
      sorts: false,
      grouping: false,
      appearance: true,
      permissions: false,
      conditionalFormatting: false,
    },
    supportsFullPage: true,
    defaultFullPage: true,
  },
  internal_resource_hub: {
    type: 'internal_resource_hub',
    label: 'Internal Resource Hub',
    icon: 'FolderOpen',
    defaultWidth: 12,
    defaultHeight: 10,
    minWidth: 8,
    minHeight: 6,
    defaultConfig: {
      title: 'Brand & Media Resources',
      table_id: '',
      resource_hub_subtitle:
        'Access official logos, brand assets, images and documents for internal use.',
      resource_hub_default_category: 'all',
      resource_hub_show_search: true,
      resource_hub_show_filters: true,
      resource_hub_show_recent: true,
      resource_hub_show_upload: true,
      resource_hub_layout_mode: 'gallery',
      resource_hub_internal_notice:
        'For internal use only. Please follow brand guidelines in all communications.',
      is_full_page: false,
    },
    applicableSettings: {
      fields: false,
      filters: false,
      sorts: false,
      grouping: false,
      appearance: true,
      permissions: false,
      conditionalFormatting: false,
    },
    supportsFullPage: true,
    defaultFullPage: false,
  },
  record_context: {
    type: 'record_context',
    label: 'Record selector',
    icon: 'List',
    defaultWidth: 6,
    defaultHeight: 4,
    minWidth: 2,
    minHeight: 2,
    defaultConfig: {
      title: 'Select record',
      table_id: '',
      displayMode: 'list',
      allowClear: true,
      selectionMode: 'single',
    },
    supportsFullPage: true,
    defaultFullPage: true,
    fullPageLayout: 'rail',
    fullPageMaxWidth: 360,
    supportsRecordPreview: true,
    defaultRecordPreview: true,
  },
}

export function getBlockDefinition(type: BlockType): BlockDefinition {
  return BLOCK_REGISTRY[type]
}

export function getAllBlockTypes(): BlockType[] {
  return Object.keys(BLOCK_REGISTRY) as BlockType[]
}
