import type { HubStore } from "@/lib/types";
import { createMerchInventorySeed } from "@/lib/merch/inventory-seed";

const now = new Date().toISOString();

export function createSeedStore(): HubStore {
  return {
    events: [
      {
        id: "evt_seed_1",
        title: "Monaco Yacht Show",
        starts_at: new Date(Date.now() + 1000 * 60 * 60 * 24 * 40).toISOString(),
        ends_at: new Date(Date.now() + 1000 * 60 * 60 * 24 * 44).toISOString(),
        location: "Monaco",
        event_type: "Trade show",
        division: "Leisure",
        notes: "Booth + press meetings.",
        link_url: "",
        created_by: "demo-staff",
        created_at: now,
        updated_at: now,
      },
      {
        id: "evt_seed_2",
        title: "Internal Q3 planning day",
        starts_at: new Date(Date.now() + 1000 * 60 * 60 * 24 * 10).toISOString(),
        ends_at: null,
        location: "Southampton office",
        event_type: "Internal",
        division: "All",
        notes: "Bring campaign briefs.",
        link_url: "",
        created_by: "demo-staff",
        created_at: now,
        updated_at: now,
      },
    ],
    event_attendance: [],
    content: [
      {
        id: "cnt_seed_1",
        title: "Summer shipping tips reel",
        channel: ["Instagram"],
        content_type: "Social",
        owner: "Sophie",
        due_date: new Date(Date.now() + 1000 * 60 * 60 * 24 * 7)
          .toISOString()
          .slice(0, 10),
        deadline_date: null,
        status: "draft",
        category: "Social Media",
        priority: "Medium",
        website: "",
        caption: "",
        theme_id: null,
        planable_url: "",
        planable_post_id: "",
        planable_group_id: "",
        planable_page_ids: [],
        last_synced_at: null,
        sync_source: "",
        asset_url: "",
        notes: "Need deck cargo B-roll.",
        created_at: now,
        updated_at: now,
      },
      {
        id: "cnt_seed_2",
        title: "LinkedIn case study â€” yacht move",
        channel: ["LinkedIn"],
        content_type: "Social",
        owner: "Marketing",
        due_date: new Date(Date.now() + 1000 * 60 * 60 * 24 * 14)
          .toISOString()
          .slice(0, 10),
        deadline_date: null,
        status: "idea",
        category: "Case study",
        priority: "",
        website: "",
        caption: "",
        theme_id: null,
        planable_url: "",
        planable_post_id: "",
        planable_group_id: "",
        planable_page_ids: [],
        last_synced_at: null,
        sync_source: "",
        asset_url: "",
        notes: "",
        created_at: now,
        updated_at: now,
      },
      {
        id: "cnt_seed_3",
        title: "Press release â€” new route",
        channel: ["PR"],
        content_type: "PR",
        owner: "Sophie",
        due_date: null,
        deadline_date: null,
        status: "review",
        category: "Press release",
        priority: "High",
        website: "",
        caption: "",
        theme_id: null,
        planable_url: "",
        planable_post_id: "",
        planable_group_id: "",
        planable_page_ids: [],
        last_synced_at: null,
        sync_source: "",
        asset_url: "",
        notes: "Legal check pending.",
        created_at: now,
        updated_at: now,
      },
      {
        id: "cnt_seed_theme_1",
        title:
          "Global forwarding is becoming more complex â€” customers expect it simpler",
        channel: ["Article"],
        content_type: "Editorial",
        owner: "Sophie",
        due_date: null,
        deadline_date: null,
        status: "draft",
        category: "Insight",
        priority: "High",
        website: "",
        caption: "",
        theme_id: "thm_seed_q3",
        planable_url: "",
        planable_post_id: "",
        planable_group_id: "",
        planable_page_ids: [],
        last_synced_at: null,
        sync_source: "",
        asset_url: "",
        notes: "Core thought-leadership piece for the quarter.",
        created_at: now,
        updated_at: now,
      },
      {
        id: "cnt_seed_theme_2",
        title: "The Middle East is still moving â€” the route looks different",
        channel: ["Case study"],
        content_type: "Editorial",
        owner: "Marketing",
        due_date: null,
        deadline_date: null,
        status: "idea",
        category: "Insight",
        priority: "",
        website: "",
        caption: "",
        theme_id: "thm_seed_q3",
        planable_url: "",
        planable_post_id: "",
        planable_group_id: "",
        planable_page_ids: [],
        last_synced_at: null,
        sync_source: "",
        asset_url: "",
        notes: "",
        created_at: now,
        updated_at: now,
      },
    ],
    sponsorships: [
      {
        id: "spn_seed_1",
        kind: "sponsorship",
        membership_type: "membership",
        partner: "Ocean Lifestyle Magazine",
        package_name: "Annual partner",
        starts_at: new Date().toISOString().slice(0, 10),
        ends_at: new Date(Date.now() + 1000 * 60 * 60 * 24 * 365)
          .toISOString()
          .slice(0, 10),
        value: "Â£12,000",
        status: "active",
        deliverables: "4 features, logo on site, 2 social mentions/month",
        owner: "Sophie",
        onedrive_url: "",
        notes: "",
        created_by: "Sophie",
        created_by_user_id: null,
        created_at: now,
        updated_at: now,
      },
      {
        id: "spn_seed_mem_1",
        kind: "membership",
        membership_type: "membership",
        partner: "British Marine",
        package_name: "Corporate membership",
        starts_at: new Date().toISOString().slice(0, 10),
        ends_at: new Date(Date.now() + 1000 * 60 * 60 * 24 * 365)
          .toISOString()
          .slice(0, 10),
        value: "Â£2,400 / year",
        status: "active",
        deliverables: "Listing, events access, member rates",
        owner: "Sophie",
        onedrive_url: "",
        notes: "Renews annually â€” diary reminder Q4.",
        created_by: "Sophie",
        created_by_user_id: null,
        created_at: now,
        updated_at: now,
      },
      {
        id: "spn_seed_mem_2",
        kind: "membership",
        membership_type: "membership",
        partner: "Logistics UK",
        package_name: "Membership",
        starts_at: new Date().toISOString().slice(0, 10),
        ends_at: null,
        value: "",
        status: "active",
        deliverables: "Policy updates, networking, awards entry",
        owner: "Marketing",
        onedrive_url: "",
        notes: "",
        created_by: "Marketing",
        created_by_user_id: null,
        created_at: now,
        updated_at: now,
      },
    ],
    contacts: [
      // —— Suppliers / companies (from Marketing Onboarding Guide) ——
      {
        id: "ctc_seed_indigo",
        kind: "company",
        name: "Indigo Print",
        organisation: "Indigo Print",
        role: "",
        email: "andy.mansfield@indigo-digiprint.com",
        phone: "",
        website: "",
        services: "Business cards and print",
        tags: ["vendor", "printer"],
        notes:
          "Primary print supplier for business cards. Contact: Andy Mansfield. Card info also in SharePoint. Always proof spelling, contact details, QR codes, logos and layout before sign-off.",
        user_id: null,
        created_at: now,
        updated_at: now,
      },
      {
        id: "ctc_seed_andy_mansfield",
        kind: "person",
        name: "Andy Mansfield",
        organisation: "Indigo Print",
        role: "Print contact",
        email: "andy.mansfield@indigo-digiprint.com",
        phone: "",
        website: "",
        services: "",
        tags: ["vendor", "printer"],
        notes: "Business cards and print support — liaise before ordering cards.",
        user_id: null,
        created_at: now,
        updated_at: now,
      },
      {
        id: "ctc_seed_ribbonworks",
        kind: "company",
        name: "Ribbonworks",
        organisation: "Ribbonworks",
        role: "",
        email: "",
        phone: "",
        website: "https://ribbonworks.co.uk",
        services: "Custom printed neck tubes / bandanas",
        tags: ["vendor", "merch"],
        notes: "Merchandise supplier for neck tubes / bandanas.",
        user_id: null,
        created_at: now,
        updated_at: now,
      },
      {
        id: "ctc_seed_northsails",
        kind: "company",
        name: "North Sails",
        organisation: "North Sails",
        role: "",
        email: "",
        phone: "",
        website: "https://www.northsails.com/",
        services: "Corporate clothing",
        tags: ["vendor", "merch"],
        notes: "Corporate clothing supplier for branded kit (Hub merch catalogue).",
        user_id: null,
        created_at: now,
        updated_at: now,
      },
      {
        id: "ctc_seed_dean_ads",
        kind: "person",
        name: "Dean",
        organisation: "UPPCYX",
        role: "Google Ads management",
        email: "dean@uppcyx.co.uk",
        phone: "",
        website: "",
        services: "",
        tags: ["vendor", "ads"],
        notes:
          "External Google Ads campaign management. Marketing should still understand basic performance and where leads come from.",
        user_id: null,
        created_at: now,
        updated_at: now,
      },
      // —— Internal key contacts (approvals / escalation) ——
      {
        id: "ctc_seed_sophie",
        kind: "person",
        name: "Sophie Edgerley",
        organisation: "Peters & May",
        role: "Marketing lead",
        email: "sophie@petersandmay.com",
        phone: "",
        website: "",
        services: "",
        tags: ["internal", "marketing"],
        notes:
          "Platform access, approvals, larger website changes, sign-off on sponsorship, events and PR. Route external announcements via Sophie.",
        user_id: null,
        created_at: now,
        updated_at: now,
      },
      {
        id: "ctc_seed_simon",
        kind: "person",
        name: "Simon Judson",
        organisation: "Peters & May",
        role: "CEO",
        email: "",
        phone: "",
        website: "",
        services: "",
        tags: ["internal", "approval"],
        notes:
          "Approves anything going external — press releases and external PR. Route via Sophie.",
        user_id: null,
        created_at: now,
        updated_at: now,
      },
      {
        id: "ctc_seed_kristina",
        kind: "person",
        name: "Kristina Webster",
        organisation: "Peters & May",
        role: "Global Sales & Marketing",
        email: "",
        phone: "",
        website: "",
        services: "",
        tags: ["internal", "marketing"],
        notes: "Senior sales & marketing lead and escalation point for marketing priorities.",
        user_id: null,
        created_at: now,
        updated_at: now,
      },
      // —— Forwarding ——
      {
        id: "ctc_seed_paul_everley",
        kind: "person",
        name: "Paul Everley",
        organisation: "Peters & May",
        role: "Global Forwarding",
        email: "",
        phone: "",
        website: "",
        services: "",
        tags: ["internal", "forwarding"],
        notes: "",
        user_id: null,
        created_at: now,
        updated_at: now,
      },
      {
        id: "ctc_seed_rasmus",
        kind: "person",
        name: "Rasmus Ollgard",
        organisation: "Peters & May",
        role: "US Forwarding",
        email: "",
        phone: "",
        website: "",
        services: "",
        tags: ["internal", "forwarding", "us"],
        notes: "",
        user_id: null,
        created_at: now,
        updated_at: now,
      },
      {
        id: "ctc_seed_joanna",
        kind: "person",
        name: "Joanna Jacks",
        organisation: "Peters & May",
        role: "UK Forwarding",
        email: "",
        phone: "",
        website: "",
        services: "",
        tags: ["internal", "forwarding", "uk"],
        notes: "",
        user_id: null,
        created_at: now,
        updated_at: now,
      },
      // —— Offices & regions ——
      {
        id: "ctc_seed_richard",
        kind: "person",
        name: "Richard Howatt",
        organisation: "Peters & May",
        role: "UK — usual contact",
        email: "",
        phone: "",
        website: "",
        services: "",
        tags: ["internal", "office", "uk"],
        notes: "",
        user_id: null,
        created_at: now,
        updated_at: now,
      },
      {
        id: "ctc_seed_chris",
        kind: "person",
        name: "Chris Perez",
        organisation: "Peters & May",
        role: "US Manager",
        email: "",
        phone: "",
        website: "",
        services: "",
        tags: ["internal", "office", "us"],
        notes: "",
        user_id: null,
        created_at: now,
        updated_at: now,
      },
      {
        id: "ctc_seed_jack",
        kind: "person",
        name: "Jack McCarthy",
        organisation: "Peters & May",
        role: "Dubai",
        email: "",
        phone: "",
        website: "",
        services: "",
        tags: ["internal", "office", "dubai"],
        notes: "",
        user_id: null,
        created_at: now,
        updated_at: now,
      },
      {
        id: "ctc_seed_inge",
        kind: "person",
        name: "Inge Valk",
        organisation: "Peters & May",
        role: "Netherlands",
        email: "",
        phone: "",
        website: "",
        services: "",
        tags: ["internal", "office", "netherlands"],
        notes: "",
        user_id: null,
        created_at: now,
        updated_at: now,
      },
      {
        id: "ctc_seed_stefano",
        kind: "person",
        name: "Stefano Grotti",
        organisation: "Peters & May",
        role: "Europe",
        email: "",
        phone: "",
        website: "",
        services: "",
        tags: ["internal", "office", "europe"],
        notes: "",
        user_id: null,
        created_at: now,
        updated_at: now,
      },
      {
        id: "ctc_seed_luke",
        kind: "person",
        name: "Luke Webster",
        organisation: "Peters & May",
        role: "Asia",
        email: "",
        phone: "",
        website: "",
        services: "",
        tags: ["internal", "office", "asia"],
        notes: "",
        user_id: null,
        created_at: now,
        updated_at: now,
      },
      // —— Divisions ——
      {
        id: "ctc_seed_robert",
        kind: "person",
        name: "Robert Blades",
        organisation: "Peters & May",
        role: "Commercial Marine Manager",
        email: "",
        phone: "",
        website: "",
        services: "",
        tags: ["internal", "division", "commercial"],
        notes: "Shipment / technical post approval for Commercial Marine.",
        user_id: null,
        created_at: now,
        updated_at: now,
      },
      {
        id: "ctc_seed_craig",
        kind: "person",
        name: "Craig Stanbury",
        organisation: "Peters & May",
        role: "Racing",
        email: "",
        phone: "",
        website: "",
        services: "",
        tags: ["internal", "division", "racing"],
        notes: "Shipment / technical post approval for Racing.",
        user_id: null,
        created_at: now,
        updated_at: now,
      },
    ],
    resources: [
      {
        id: "res_seed_1",
        title: "Brand guidelines (PDF)",
        description: "PM-Brand-Guide_FINAL.pdf — also in Library → Brand / SharePoint › Marketing › Brand Guidelines",
        url: "https://hwtycgvclhckglmuwnmw.supabase.co/storage/v1/object/public/attachments/attachments/table_media_1768074185692/19e724de-39c2-4ee5-b545-dae584996d8c/media/4363f3e1-1bb0-49f4-ad10-7f6d92ea52e0.pdf",
        category: "Brand",
        created_at: now,
        updated_at: now,
      },
      {
        id: "res_seed_2",
        title: "Press & media enquiries",
        description: "Route press requests to marketing",
        url: "mailto:marketing@petersandmay.com",
        category: "Press",
        created_at: now,
        updated_at: now,
      },
      {
        id: "res_seed_3",
        title: "Meet the team / careers",
        description: "Live roles and team page for social hiring posts",
        url: "https://www.petersandmay.com/about-us/meet-the-team/",
        category: "Web",
        created_at: now,
        updated_at: now,
      },
      {
        id: "res_seed_drive",
        title: "Google Drive — shared marketing materials",
        description: "Shared files and materials shared externally or across teams",
        url: "https://drive.google.com/drive/folders/1pl2aGuYc0jcbjFlV9QrSZdvYOXDjZyTl",
        category: "General",
        created_at: now,
        updated_at: now,
      },
      {
        id: "res_seed_frameio",
        title: "Frame.io — maritime filming / drone footage",
        description: "Drone footage and video assets from the maritime filming retainer — confirm link is current",
        url: "https://next.frame.io/share/0366a468-c4d8-416a-8327-cb26f0edbbb/258e458e-4dc1-4e60-ad05-1c77db6ca531",
        category: "General",
        created_at: now,
        updated_at: now,
      },
      {
        id: "res_seed_qr",
        title: "QR Code Generator",
        description: "QR codes for printed material, events and campaigns",
        url: "https://app.qr-code-generator.com/",
        category: "General",
        created_at: now,
        updated_at: now,
      },
      {
        id: "res_seed_cms",
        title: "Marketing website / CMS",
        description: "WordPress — blogs and marketing content updates",
        url: "https://marketing.petersandmay.com/",
        category: "Web",
        created_at: now,
        updated_at: now,
      },
      {
        id: "res_seed_prowly",
        title: "Prowly newsroom",
        description: "PR newsroom, press releases and media activity",
        url: "https://petersandmay.prowly.com/",
        category: "Press",
        created_at: now,
        updated_at: now,
      },
      {
        id: "res_seed_sailing",
        title: "Sailing schedules page",
        description: "Public sailing schedule — for social CTAs",
        url: "https://www.petersandmay.com/sailing-schedules/",
        category: "Web",
        created_at: now,
        updated_at: now,
      },
    ],
    reports: [
      {
        id: "rpt_seed_looker",
        title: "General marketing report",
        description: "Looker Studio / Data Studio — website, social, campaigns, enquiries",
        url: "https://datastudio.google.com/reporting/82d0ce51-116a-4361-827b-2afff140c2c8",
        category: "Dashboards",
        tool: "Looker Studio",
        created_at: now,
        updated_at: now,
      },
      {
        id: "rpt_seed_ads",
        title: "Google Ads (external)",
        description: "Managed externally by Dean (UPPCYX) — review performance with marketing",
        url: "https://ads.google.com/",
        category: "Ads",
        tool: "Google Ads",
        created_at: now,
        updated_at: now,
      },
      {
        id: "rpt_seed_seo",
        title: "SEO rankings & visibility",
        description: "Keyword positions, competitors, site audit",
        url: "https://seranking.com/",
        category: "SEO",
        tool: "SE Ranking",
        created_at: now,
        updated_at: now,
      },
      {
        id: "rpt_seed_enq",
        title: "Web enquiries",
        description: "In-hub list — see Web Enquiries tab",
        url: "/app/enquiries",
        category: "Enquiries",
        tool: "Sheet / CRM",
        created_at: now,
        updated_at: now,
      },
      {
        id: "rpt_seed_social",
        title: "Social performance",
        description: "Reach and engagement — Planable analytics or native insights",
        url: "https://app.planable.io/",
        category: "Social",
        tool: "Planable / native",
        created_at: now,
        updated_at: now,
      },
      {
        id: "rpt_seed_linkedin",
        title: "LinkedIn paid campaigns",
        description: "Campaign Manager — spend, delivery, and website visits",
        url: "https://www.linkedin.com/campaignmanager/",
        category: "Ads",
        tool: "LinkedIn Campaign Manager",
        created_at: now,
        updated_at: now,
      },
      {
        id: "rpt_seed_hubspot",
        title: "HubSpot",
        description: "Marketing / CRM access where relevant",
        url: "https://app-eu1.hubspot.com/",
        category: "Dashboards",
        tool: "Other",
        created_at: now,
        updated_at: now,
      },
    ],
    paid_campaigns: [
      {
        id: "pc_seed_linkedin_shipping",
        name: "International Shipping Guide",
        platform: "LinkedIn",
        status: "complete",
        external_id: "1464680924",
        external_url: "https://www.linkedin.com/campaignmanager/",
        starts_at: null,
        ends_at: null,
        spent: 400,
        goal: "Website visits",
        key_results: "139 website visits",
        cost_per_result: 2.88,
        impressions: 28056,
        clicks: 139,
        ctr: "0.5%",
        landing_clicks: 139,
        engagement_rate: "1.12%",
        notes:
          "Single-image ad promoting the international yacht shipping guide. Promoted post copy references lnkd.in/eFhR_TwA.",
        theme_id: "thm_seed_q3",
        content_id: null,
        event_id: null,
        created_at: now,
        updated_at: now,
      },
      {
        id: "pc_seed_google_ads",
        name: "Yacht transport — search",
        platform: "Google Ads",
        status: "active",
        external_id: "",
        external_url: "https://ads.google.com/",
        starts_at: null,
        ends_at: null,
        spent: null,
        goal: "Leads / enquiries",
        key_results: "",
        cost_per_result: null,
        impressions: null,
        clicks: null,
        ctr: "",
        landing_clicks: null,
        engagement_rate: "",
        notes:
          "Placeholder — paste spend and results from Google Ads when reviewing. Enquiry attribution is in Web Enquiries.",
        theme_id: null,
        content_id: null,
        event_id: null,
        created_at: now,
        updated_at: now,
      },
    ],
    advertisements: [
      {
        id: "ad_seed_seahorse",
        title: "Seahorse Magazine — display ad",
        publication: "Seahorse Magazine",
        status: "active",
        starts_at: "2026-01-01",
        ends_at: "2026-12-31",
        artwork_url: "",
        agreement_url: "",
        notes:
          "Placeholder — attach current artwork and the insertion agreement, then update run dates.",
        created_at: now,
        updated_at: now,
      },
    ],
    platform_credentials: [
      {
        id: "cred_seed_planable",
        platform: "Planable",
        url: "https://app.planable.io/",
        username: "",
        password: "",
        notes:
          "Social scheduling, approvals and content planning. Request access from Sophie.",
        created_at: now,
        updated_at: now,
      },
      {
        id: "cred_seed_canva",
        platform: "Canva",
        url: "https://www.canva.com/",
        username: "",
        password: "",
        notes:
          "Design templates, social graphics, simple artwork. Request access from Sophie.",
        created_at: now,
        updated_at: now,
      },
      {
        id: "cred_seed_meta",
        platform: "Meta Business Suite",
        url: "https://business.facebook.com/",
        username: "",
        password: "",
        notes:
          "Facebook and Instagram management. Request access from Sophie.",
        created_at: now,
        updated_at: now,
      },
      {
        id: "cred_seed_cms",
        platform: "Website CMS",
        url: "https://marketing.petersandmay.com/",
        username: "",
        password: "",
        notes:
          "WordPress — blogs and marketing content. Request access from Sophie.",
        created_at: now,
        updated_at: now,
      },
      {
        id: "cred_seed_prowly",
        platform: "Prowly",
        url: "https://petersandmay.prowly.com/",
        username: "",
        password: "",
        notes: "PR newsroom — press releases and media activity. Request access from Sophie.",
        created_at: now,
        updated_at: now,
      },
      {
        id: "cred_seed_hubspot",
        platform: "HubSpot",
        url: "https://app-eu1.hubspot.com/",
        username: "",
        password: "",
        notes: "Marketing / CRM where relevant. Request access from Sophie.",
        created_at: now,
        updated_at: now,
      },
      {
        id: "cred_seed_looker",
        platform: "Looker Studio",
        url: "https://datastudio.google.com/reporting/82d0ce51-116a-4361-827b-2afff140c2c8",
        username: "",
        password: "",
        notes: "General marketing reporting dashboard. Usually Google account access.",
        created_at: now,
        updated_at: now,
      },
      {
        id: "cred_seed_qr",
        platform: "QR Code Generator",
        url: "https://app.qr-code-generator.com/",
        username: "",
        password: "",
        notes: "QR codes for print, events and campaigns. Request access from Sophie.",
        created_at: now,
        updated_at: now,
      },
      {
        id: "cred_seed_frameio",
        platform: "Frame.io",
        url: "https://next.frame.io/share/0366a468-c4d8-416a-8327-cb26f0edbbb/258e458e-4dc1-4e60-ad05-1c77db6ca531",
        username: "",
        password: "",
        notes:
          "Maritime filming / drone footage retainer. Confirm share link is current. Request access from Sophie.",
        created_at: now,
        updated_at: now,
      },
      {
        id: "cred_seed_google_ads",
        platform: "Google Ads",
        url: "https://ads.google.com/",
        username: "",
        password: "",
        notes:
          "Currently managed externally by Dean (dean@uppcyx.co.uk). Marketing reviews performance; do not share passwords casually.",
        created_at: now,
        updated_at: now,
      },
      {
        id: "cred_seed_linkedin",
        platform: "LinkedIn Ads",
        url: "https://www.linkedin.com/campaignmanager/",
        username: "",
        password: "",
        notes: "Company page / Campaign Manager. Request access from Sophie.",
        created_at: now,
        updated_at: now,
      },
    ],
    themes: [
      {
        id: "thm_seed_q1",
        title: "Planning & Preparation",
        quarter: "Q1",
        year: 2026,
        status: "previous",
        summary: "Set the yearâ€™s narrative and prep major campaigns.",
        created_at: now,
        updated_at: now,
      },
      {
        id: "thm_seed_q2",
        title: "Operational credibility",
        quarter: "Q2",
        year: 2026,
        status: "previous",
        summary: "Show how complex moves become simple for customers.",
        created_at: now,
        updated_at: now,
      },
      {
        id: "thm_seed_q3",
        title: "Reliability & execution",
        quarter: "Q3",
        year: 2026,
        status: "active",
        summary: "Proof points from live projects and on-time delivery.",
        created_at: now,
        updated_at: now,
      },
      {
        id: "thm_seed_q4",
        title: "Risk, control & reflection",
        quarter: "Q4",
        year: 2026,
        status: "upcoming",
        summary: "Year-end learnings and forward look.",
        created_at: now,
        updated_at: now,
      },
    ],
    theme_mains: [
      {
        id: "tmc_seed_1",
        theme_id: "thm_seed_q3",
        content_id: "cnt_seed_theme_1",
        title:
          "Global forwarding is becoming more complex â€” customers expect it simpler",
        channel: "Article",
        owner: "Sophie",
        status: "draft",
        notes: "Core thought-leadership piece for the quarter.",
        created_at: now,
        updated_at: now,
      },
      {
        id: "tmc_seed_2",
        theme_id: "thm_seed_q3",
        content_id: "cnt_seed_theme_2",
        title: "The Middle East is still moving â€” the route looks different",
        channel: "Case study",
        owner: "Marketing",
        status: "idea",
        notes: "",
        created_at: now,
        updated_at: now,
      },
    ],
    theme_offshoots: [
      {
        id: "tof_seed_1",
        main_content_id: "tmc_seed_1",
        title: "Carousel: 5 ways we simplify complex moves",
        channel: "LinkedIn",
        owner: "Sophie",
        status: "idea",
        notes: "Pull quotes from the main article.",
        created_at: now,
        updated_at: now,
      },
      {
        id: "tof_seed_2",
        main_content_id: "tmc_seed_1",
        title: "Short reel â€” deck cargo B-roll",
        channel: "Instagram",
        owner: "Sophie",
        status: "idea",
        notes: "",
        created_at: now,
        updated_at: now,
      },
      {
        id: "tof_seed_3",
        main_content_id: "tmc_seed_2",
        title: "Staff quote cards for social",
        channel: "LinkedIn",
        owner: "Marketing",
        status: "idea",
        notes: "",
        created_at: now,
        updated_at: now,
      },
    ],
    merch_orders: [
      {
        id: "mrc_seed_1",
        item: "Polo â€” Regatta (polyester)",
        fit: "female",
        size: "M",
        quantity: 1,
        colour: "Navy",
        logo: "Bespoke Logistics",
        requested_for: "Sophie Edgerley",
        requested_for_contact_id: null,
        office: "Southampton",
        needed_by: new Date(Date.now() + 1000 * 60 * 60 * 24 * 21)
          .toISOString()
          .slice(0, 10),
        status: "requested",
        notes: "North Sails Regatta polo for show season.",
        created_by: "Sophie",
        created_by_user_id: null,
        created_at: now,
        updated_at: now,
      },
      {
        id: "mrc_seed_2",
        item: "Gilet â€” Marstrand (navy)",
        fit: "male",
        size: "L",
        quantity: 1,
        colour: "Navy",
        logo: "Global Yacht Transport",
        requested_for: "Ops â€” Southampton",
        requested_for_contact_id: null,
        office: "Southampton",
        needed_by: null,
        status: "ordered",
        notes: "Navy Marstrand quilted vest.",
        created_by: "Marketing",
        created_by_user_id: null,
        created_at: now,
        updated_at: now,
      },
      {
        id: "mrc_seed_3",
        item: "Sailor jacket (navy)",
        fit: "male",
        size: "XL",
        quantity: 2,
        colour: "Navy",
        logo: "Forwarding",
        requested_for: "Loadmasters",
        requested_for_contact_id: null,
        office: "Southampton",
        needed_by: new Date(Date.now() + 1000 * 60 * 60 * 24 * 45)
          .toISOString()
          .slice(0, 10),
        status: "approved",
        notes: "North Sails sailor jacket, net lined.",
        created_by: "Sophie",
        created_by_user_id: null,
        created_at: now,
        updated_at: now,
      },
    ],
    merch_inventory: createMerchInventorySeed(now),
    merch_catalogue: [],
    staff_requests: [
      {
        id: "sr_seed_1",
        kind: "asset",
        category: "Image",
        title: "High-res yacht load photos for LinkedIn",
        details: "Need 4â€“6 images from Rotterdam project for next weekâ€™s post.",
        requested_by: "Marketing",
        needed_by: new Date(Date.now() + 1000 * 60 * 60 * 24 * 7)
          .toISOString()
          .slice(0, 10),
        attachment_url: "",
        status: "open",
        created_at: now,
        updated_at: now,
      },
      {
        id: "sr_seed_2",
        kind: "social_form",
        category: "",
        title: "Internal shout-out form for staff wins",
        details:
          "Simple form so offices can submit colleague wins for social.",
        requested_by: "Sophie",
        needed_by: null,
        attachment_url: "",
        status: "in_progress",
        created_at: now,
        updated_at: now,
      },
    ],
    awards: [
      {
        id: "awd_seed_1",
        title: "Seatrade Maritime Awards",
        organisation: "Seatrade",
        category: "Logistics / maritime",
        year: 2026,
        status: "entering",
        ceremony_at: new Date(Date.now() + 1000 * 60 * 60 * 24 * 30)
          .toISOString()
          .slice(0, 10),
        owner: "Sophie",
        event_id: null,
        notes: "Track entry deadline and supporting case study.",
        created_at: now,
        updated_at: now,
      },
      {
        id: "awd_seed_2",
        title: "Export & Freight Awards",
        organisation: "Export & Freight",
        category: "Freight forwarder",
        year: 2026,
        status: "watching",
        ceremony_at: new Date(Date.now() + 1000 * 60 * 60 * 24 * 90)
          .toISOString()
          .slice(0, 10),
        owner: "Marketing",
        event_id: null,
        notes: "",
        created_at: now,
        updated_at: now,
      },
      {
        id: "awd_seed_3",
        title: "World Superyacht Awards",
        organisation: "Boat International",
        category: "Support services",
        year: 2026,
        status: "submitted",
        ceremony_at: null,
        owner: "Sophie",
        event_id: null,
        notes: "Linked to yacht logistics work.",
        created_at: now,
        updated_at: now,
      },
    ],
    tasks: [
      {
        id: "tsk_seed_1",
        title: "Update boat show attendance sheet",
        details: "Confirm whoâ€™s going to Monaco and Southampton.",
        due_date: new Date(Date.now() + 1000 * 60 * 60 * 24 * 5)
          .toISOString()
          .slice(0, 10),
        start_date: new Date(Date.now() + 1000 * 60 * 60 * 24 * 2)
          .toISOString()
          .slice(0, 10),
        category: "Events",
        status: "todo",
        owner: "Sophie",
        related_type: "",
        related_id: null,
        created_at: now,
        updated_at: now,
      },
      {
        id: "tsk_seed_2",
        title: "Add new testimonials to website",
        details: "",
        start_date: null,
        due_date: null,
        category: "Website",
        status: "doing",
        owner: "Marketing",
        related_type: "",
        related_id: null,
        created_at: now,
        updated_at: now,
      },
    ],
    hub_users: [
      {
        id: "usr_seed_1",
        email: "marketing@petersandmay.com",
        full_name: "Marketing Team",
        role: "admin",
        notes: "Full hub access",
        created_at: now,
        updated_at: now,
      },
      {
        id: "usr_seed_2",
        email: "sophie@petersandmay.com",
        full_name: "Sophie Edgerley",
        role: "member",
        notes: "Day-to-day marketing",
        created_at: now,
        updated_at: now,
      },
      {
        id: "usr_seed_3",
        email: "press@example.com",
        full_name: "External press contact",
        role: "external",
        notes: "Media downloads only",
        created_at: now,
        updated_at: now,
      },
    ],
    access_requests: [],
    page_notes: {},
    field_extras: {},
  };
}

