import type { HubStore } from "@/lib/types";
import { createMerchInventorySeed } from "@/lib/merch/inventory-seed";

const now = new Date().toISOString();

export function createSeedStore(): HubStore {
  return {
    events: [
      {
        id: "evt_seed_1",
        title: "Monaco Yacht Show",
        starts_at: new Date(Date.now() + 1000 * 60 * 60 * 24 * 40).toISOString(),
        ends_at: new Date(Date.now() + 1000 * 60 * 60 * 24 * 44).toISOString(),
        location: "Monaco",
        event_type: "Trade show",
        division: "Leisure",
        notes: "Booth + press meetings.",
        link_url: "",
        created_by: "demo-staff",
        created_at: now,
        updated_at: now,
      },
      {
        id: "evt_seed_2",
        title: "Internal Q3 planning day",
        starts_at: new Date(Date.now() + 1000 * 60 * 60 * 24 * 10).toISOString(),
        ends_at: null,
        location: "Southampton office",
        event_type: "Internal",
        division: "All",
        notes: "Bring campaign briefs.",
        link_url: "",
        created_by: "demo-staff",
        created_at: now,
        updated_at: now,
      },
    ],
    event_attendance: [],
    content: [
      {
        id: "cnt_seed_1",
        title: "Summer shipping tips reel",
        channel: ["Instagram"],
        content_type: "Social",
        owner: "Sophie",
        due_date: new Date(Date.now() + 1000 * 60 * 60 * 24 * 7)
          .toISOString()
          .slice(0, 10),
        deadline_date: null,
        status: "draft",
        category: "Social Media",
        priority: "Medium",
        website: "",
        caption: "",
        theme_id: null,
        planable_url: "",
        asset_url: "",
        notes: "Need deck cargo B-roll.",
        created_at: now,
        updated_at: now,
      },
      {
        id: "cnt_seed_2",
        title: "LinkedIn case study — yacht move",
        channel: ["LinkedIn"],
        content_type: "Social",
        owner: "Marketing",
        due_date: new Date(Date.now() + 1000 * 60 * 60 * 24 * 14)
          .toISOString()
          .slice(0, 10),
        deadline_date: null,
        status: "idea",
        category: "Case study",
        priority: "",
        website: "",
        caption: "",
        theme_id: null,
        planable_url: "",
        asset_url: "",
        notes: "",
        created_at: now,
        updated_at: now,
      },
      {
        id: "cnt_seed_3",
        title: "Press release — new route",
        channel: ["PR"],
        content_type: "PR",
        owner: "Sophie",
        due_date: null,
        deadline_date: null,
        status: "review",
        category: "Press release",
        priority: "High",
        website: "",
        caption: "",
        theme_id: null,
        planable_url: "",
        asset_url: "",
        notes: "Legal check pending.",
        created_at: now,
        updated_at: now,
      },
      {
        id: "cnt_seed_theme_1",
        title:
          "Global forwarding is becoming more complex — customers expect it simpler",
        channel: ["Article"],
        content_type: "Editorial",
        owner: "Sophie",
        due_date: null,
        deadline_date: null,
        status: "draft",
        category: "Insight",
        priority: "High",
        website: "",
        caption: "",
        theme_id: "thm_seed_q3",
        planable_url: "",
        asset_url: "",
        notes: "Core thought-leadership piece for the quarter.",
        created_at: now,
        updated_at: now,
      },
      {
        id: "cnt_seed_theme_2",
        title: "The Middle East is still moving — the route looks different",
        channel: ["Case study"],
        content_type: "Editorial",
        owner: "Marketing",
        due_date: null,
        deadline_date: null,
        status: "idea",
        category: "Insight",
        priority: "",
        website: "",
        caption: "",
        theme_id: "thm_seed_q3",
        planable_url: "",
        asset_url: "",
        notes: "",
        created_at: now,
        updated_at: now,
      },
    ],
    sponsorships: [
      {
        id: "spn_seed_1",
        kind: "sponsorship",
        partner: "Ocean Lifestyle Magazine",
        package_name: "Annual partner",
        starts_at: new Date().toISOString().slice(0, 10),
        ends_at: new Date(Date.now() + 1000 * 60 * 60 * 24 * 365)
          .toISOString()
          .slice(0, 10),
        value: "£12,000",
        status: "active",
        deliverables: "4 features, logo on site, 2 social mentions/month",
        owner: "Sophie",
        onedrive_url: "",
        notes: "",
        created_at: now,
        updated_at: now,
      },
      {
        id: "spn_seed_mem_1",
        kind: "membership",
        partner: "British Marine",
        package_name: "Corporate membership",
        starts_at: new Date().toISOString().slice(0, 10),
        ends_at: new Date(Date.now() + 1000 * 60 * 60 * 24 * 365)
          .toISOString()
          .slice(0, 10),
        value: "£2,400 / year",
        status: "active",
        deliverables: "Listing, events access, member rates",
        owner: "Sophie",
        onedrive_url: "",
        notes: "Renews annually — diary reminder Q4.",
        created_at: now,
        updated_at: now,
      },
      {
        id: "spn_seed_mem_2",
        kind: "membership",
        partner: "Logistics UK",
        package_name: "Membership",
        starts_at: new Date().toISOString().slice(0, 10),
        ends_at: null,
        value: "",
        status: "active",
        deliverables: "Policy updates, networking, awards entry",
        owner: "Marketing",
        onedrive_url: "",
        notes: "",
        created_at: now,
        updated_at: now,
      },
    ],
    contacts: [
      {
        id: "ctc_seed_1",
        name: "Alex Rivera",
        organisation: "Marine Trade Weekly",
        role: "Editor",
        email: "alex@example.com",
        phone: "",
        tags: ["press"],
        notes: "Prefers emailed exclusives.",
        user_id: null,
        created_at: now,
        updated_at: now,
      },
      {
        id: "ctc_seed_2",
        name: "Jordan Lee",
        organisation: "Harbour Events Ltd",
        role: "Partnerships",
        email: "jordan@example.com",
        phone: "",
        tags: ["partner", "venue"],
        notes: "",
        user_id: null,
        created_at: now,
        updated_at: now,
      },
    ],
    resources: [
      {
        id: "res_seed_1",
        title: "Brand guidelines (PDF)",
        description: "Full brand guide — also in Library → Brand",
        url: "https://hwtycgvclhckglmuwnmw.supabase.co/storage/v1/object/public/attachments/attachments/table_media_1768074185692/19e724de-39c2-4ee5-b545-dae584996d8c/media/4363f3e1-1bb0-49f4-ad10-7f6d92ea52e0.pdf",
        category: "Brand",
        created_at: now,
        updated_at: now,
      },
      {
        id: "res_seed_2",
        title: "Press & media enquiries",
        description: "Route press requests to marketing",
        url: "mailto:marketing@petersandmay.com",
        category: "Press",
        created_at: now,
        updated_at: now,
      },
      {
        id: "res_seed_3",
        title: "Careers page",
        description: "Live roles for social hiring posts",
        url: "https://www.petersandmay.com/about-us/careers/",
        category: "Web",
        created_at: now,
        updated_at: now,
      },
    ],
    reports: [
      {
        id: "rpt_seed_ga",
        title: "Website traffic",
        description: "Sessions, users, top pages, traffic sources",
        url: "https://analytics.google.com/",
        category: "Website",
        tool: "Google Analytics",
        created_at: now,
        updated_at: now,
      },
      {
        id: "rpt_seed_ads",
        title: "Paid search & display",
        description: "Campaign spend, clicks, conversions",
        url: "https://ads.google.com/",
        category: "Ads",
        tool: "Google Ads",
        created_at: now,
        updated_at: now,
      },
      {
        id: "rpt_seed_seo",
        title: "SEO rankings & visibility",
        description: "Keyword positions, competitors, site audit",
        url: "https://seranking.com/",
        category: "SEO",
        tool: "SE Ranking",
        created_at: now,
        updated_at: now,
      },
      {
        id: "rpt_seed_looker",
        title: "Marketing overview dashboard",
        description: "Combined Looker Studio / Data Studio report (paste your share link)",
        url: "https://lookerstudio.google.com/",
        category: "Dashboards",
        tool: "Looker Studio",
        created_at: now,
        updated_at: now,
      },
      {
        id: "rpt_seed_enq",
        title: "Web enquiries",
        description: "In-hub list — see Web Enquiries tab (or paste an external sheet URL)",
        url: "/app/enquiries",
        category: "Enquiries",
        tool: "Sheet / CRM",
        created_at: now,
        updated_at: now,
      },
      {
        id: "rpt_seed_social",
        title: "Social performance",
        description: "Reach and engagement — Planable analytics or native insights",
        url: "https://app.planable.io/",
        category: "Social",
        tool: "Planable / native",
        created_at: now,
        updated_at: now,
      },
    ],
    themes: [
      {
        id: "thm_seed_q1",
        title: "Planning & Preparation",
        quarter: "Q1",
        year: 2026,
        status: "previous",
        summary: "Set the year’s narrative and prep major campaigns.",
        created_at: now,
        updated_at: now,
      },
      {
        id: "thm_seed_q2",
        title: "Operational credibility",
        quarter: "Q2",
        year: 2026,
        status: "previous",
        summary: "Show how complex moves become simple for customers.",
        created_at: now,
        updated_at: now,
      },
      {
        id: "thm_seed_q3",
        title: "Reliability & execution",
        quarter: "Q3",
        year: 2026,
        status: "active",
        summary: "Proof points from live projects and on-time delivery.",
        created_at: now,
        updated_at: now,
      },
      {
        id: "thm_seed_q4",
        title: "Risk, control & reflection",
        quarter: "Q4",
        year: 2026,
        status: "upcoming",
        summary: "Year-end learnings and forward look.",
        created_at: now,
        updated_at: now,
      },
    ],
    theme_mains: [
      {
        id: "tmc_seed_1",
        theme_id: "thm_seed_q3",
        content_id: "cnt_seed_theme_1",
        title:
          "Global forwarding is becoming more complex — customers expect it simpler",
        channel: "Article",
        owner: "Sophie",
        status: "draft",
        notes: "Core thought-leadership piece for the quarter.",
        created_at: now,
        updated_at: now,
      },
      {
        id: "tmc_seed_2",
        theme_id: "thm_seed_q3",
        content_id: "cnt_seed_theme_2",
        title: "The Middle East is still moving — the route looks different",
        channel: "Case study",
        owner: "Marketing",
        status: "idea",
        notes: "",
        created_at: now,
        updated_at: now,
      },
    ],
    theme_offshoots: [
      {
        id: "tof_seed_1",
        main_content_id: "tmc_seed_1",
        title: "Carousel: 5 ways we simplify complex moves",
        channel: "LinkedIn",
        owner: "Sophie",
        status: "idea",
        notes: "Pull quotes from the main article.",
        created_at: now,
        updated_at: now,
      },
      {
        id: "tof_seed_2",
        main_content_id: "tmc_seed_1",
        title: "Short reel — deck cargo B-roll",
        channel: "Instagram",
        owner: "Sophie",
        status: "idea",
        notes: "",
        created_at: now,
        updated_at: now,
      },
      {
        id: "tof_seed_3",
        main_content_id: "tmc_seed_2",
        title: "Staff quote cards for social",
        channel: "LinkedIn",
        owner: "Marketing",
        status: "idea",
        notes: "",
        created_at: now,
        updated_at: now,
      },
    ],
    merch_orders: [
      {
        id: "mrc_seed_1",
        item: "Polo — Regatta (polyester)",
        fit: "female",
        size: "M",
        quantity: 1,
        colour: "Navy",
        logo: "Commercial",
        requested_for: "Sophie Edgerley",
        office: "Southampton",
        needed_by: new Date(Date.now() + 1000 * 60 * 60 * 24 * 21)
          .toISOString()
          .slice(0, 10),
        status: "requested",
        notes: "North Sails Regatta polo for show season.",
        created_by: "Sophie",
        created_by_user_id: null,
        created_at: now,
        updated_at: now,
      },
      {
        id: "mrc_seed_2",
        item: "Gilet — Marstrand (navy)",
        fit: "male",
        size: "L",
        quantity: 1,
        colour: "Navy",
        logo: "Yacht Transport",
        requested_for: "Ops — Southampton",
        office: "Southampton",
        needed_by: null,
        status: "ordered",
        notes: "Navy Marstrand quilted vest.",
        created_by: "Marketing",
        created_by_user_id: null,
        created_at: now,
        updated_at: now,
      },
      {
        id: "mrc_seed_3",
        item: "Sailor jacket (navy)",
        fit: "male",
        size: "XL",
        quantity: 2,
        colour: "Navy",
        logo: "Forwarding",
        requested_for: "Loadmasters",
        office: "Southampton",
        needed_by: new Date(Date.now() + 1000 * 60 * 60 * 24 * 45)
          .toISOString()
          .slice(0, 10),
        status: "approved",
        notes: "North Sails sailor jacket, net lined.",
        created_by: "Sophie",
        created_by_user_id: null,
        created_at: now,
        updated_at: now,
      },
    ],
    merch_inventory: createMerchInventorySeed(now),
    staff_requests: [
      {
        id: "sr_seed_1",
        kind: "asset",
        category: "Image",
        title: "High-res yacht load photos for LinkedIn",
        details: "Need 4–6 images from Rotterdam project for next week’s post.",
        requested_by: "Marketing",
        needed_by: new Date(Date.now() + 1000 * 60 * 60 * 24 * 7)
          .toISOString()
          .slice(0, 10),
        attachment_url: "",
        status: "open",
        created_at: now,
        updated_at: now,
      },
      {
        id: "sr_seed_2",
        kind: "social_form",
        category: "",
        title: "Internal shout-out form for staff wins",
        details:
          "Simple form so offices can submit colleague wins for social.",
        requested_by: "Sophie",
        needed_by: null,
        attachment_url: "",
        status: "in_progress",
        created_at: now,
        updated_at: now,
      },
    ],
    awards: [
      {
        id: "awd_seed_1",
        title: "Seatrade Maritime Awards",
        organisation: "Seatrade",
        category: "Logistics / maritime",
        year: 2026,
        status: "entering",
        ceremony_at: new Date(Date.now() + 1000 * 60 * 60 * 24 * 30)
          .toISOString()
          .slice(0, 10),
        owner: "Sophie",
        event_id: null,
        notes: "Track entry deadline and supporting case study.",
        created_at: now,
        updated_at: now,
      },
      {
        id: "awd_seed_2",
        title: "Export & Freight Awards",
        organisation: "Export & Freight",
        category: "Freight forwarder",
        year: 2026,
        status: "watching",
        ceremony_at: new Date(Date.now() + 1000 * 60 * 60 * 24 * 90)
          .toISOString()
          .slice(0, 10),
        owner: "Marketing",
        event_id: null,
        notes: "",
        created_at: now,
        updated_at: now,
      },
      {
        id: "awd_seed_3",
        title: "World Superyacht Awards",
        organisation: "Boat International",
        category: "Support services",
        year: 2026,
        status: "submitted",
        ceremony_at: null,
        owner: "Sophie",
        event_id: null,
        notes: "Linked to yacht logistics work.",
        created_at: now,
        updated_at: now,
      },
    ],
    tasks: [
      {
        id: "tsk_seed_1",
        title: "Update boat show attendance sheet",
        details: "Confirm who’s going to Monaco and Southampton.",
        due_date: new Date(Date.now() + 1000 * 60 * 60 * 24 * 5)
          .toISOString()
          .slice(0, 10),
        category: "Events",
        status: "todo",
        owner: "Sophie",
        related_type: "",
        related_id: null,
        created_at: now,
        updated_at: now,
      },
      {
        id: "tsk_seed_2",
        title: "Add new testimonials to website",
        details: "",
        due_date: null,
        category: "Website",
        status: "doing",
        owner: "Marketing",
        related_type: "",
        related_id: null,
        created_at: now,
        updated_at: now,
      },
    ],
    hub_users: [
      {
        id: "usr_seed_1",
        email: "marketing@petersandmay.com",
        full_name: "Marketing Team",
        role: "admin",
        notes: "Full hub access",
        created_at: now,
        updated_at: now,
      },
      {
        id: "usr_seed_2",
        email: "sophie@petersandmay.com",
        full_name: "Sophie Edgerley",
        role: "member",
        notes: "Day-to-day marketing",
        created_at: now,
        updated_at: now,
      },
      {
        id: "usr_seed_3",
        email: "press@example.com",
        full_name: "External press contact",
        role: "external",
        notes: "Media downloads only",
        created_at: now,
        updated_at: now,
      },
    ],
    access_requests: [],
    page_notes: {},
    field_extras: {},
  };
}
