import type { MerchInventoryItem } from "@/lib/types";

/** Current on-hand stock (Southampton kit cupboard), Jul 2026. */
export function createMerchInventorySeed(
  now: string
): MerchInventoryItem[] {
  const rows: Omit<
    MerchInventoryItem,
    "id" | "created_at" | "updated_at" | "image_url"
  >[] = [
    {
      item: "Gilet — Marstrand (navy)",
      brand: "North Sails",
      fit: "male",
      size: "XL",
      colour: "Navy",
      quantity: 2,
      notes: "",
    },
    {
      item: "Backpack",
      brand: "BagBase",
      fit: "",
      size: "N/A",
      colour: "Navy",
      quantity: 1,
      notes: "",
    },
    {
      item: "Gilet — Marstrand (navy)",
      brand: "North Sails",
      fit: "female",
      size: "S",
      colour: "Navy",
      quantity: 1,
      notes: "",
    },
    {
      item: "Polo — Regatta (polyester)",
      brand: "North Sails",
      fit: "female",
      size: "S",
      colour: "Navy",
      quantity: 1,
      notes: "",
    },
    {
      item: "Sailor jacket (navy)",
      brand: "North Sails",
      fit: "male",
      size: "M",
      colour: "Navy",
      quantity: 1,
      notes: "",
    },
    {
      item: "Polo — Pique (cotton)",
      brand: "North Sails",
      fit: "female",
      size: "XL",
      colour: "White",
      quantity: 1,
      notes: "",
    },
    {
      item: "Polo — Regatta (polyester)",
      brand: "North Sails",
      fit: "male",
      size: "M",
      colour: "Navy",
      quantity: 1,
      notes: "",
    },
    {
      item: "Polo — Regatta (polyester)",
      brand: "North Sails",
      fit: "male",
      size: "L",
      colour: "Navy",
      quantity: 1,
      notes: "",
    },
    {
      item: "Collared shirt (white)",
      brand: "Henbury",
      fit: "male",
      size: "L",
      colour: "White",
      quantity: 1,
      notes: "",
    },
    {
      item: "Premier white shirt",
      brand: "Premier",
      fit: "male",
      size: "L",
      colour: "White",
      quantity: 2,
      notes: "",
    },
    {
      item: "Premier white shirt",
      brand: "Premier",
      fit: "male",
      size: "M",
      colour: "White",
      quantity: 2,
      notes: "",
    },
    {
      item: "Sailor jacket (navy)",
      brand: "North Sails",
      fit: "female",
      size: "S",
      colour: "Navy",
      quantity: 1,
      notes: "",
    },
    {
      item: "Gilet — Marstrand (navy)",
      brand: "North Sails",
      fit: "male",
      size: "M",
      colour: "Navy",
      quantity: 1,
      notes: "",
    },
    {
      item: "Polo — Regatta (polyester)",
      brand: "North Sails",
      fit: "female",
      size: "S",
      colour: "White",
      quantity: 1,
      notes: "Yacht transfer branding",
    },
    {
      item: "Polo — Regatta (polyester)",
      brand: "North Sails",
      fit: "female",
      size: "L",
      colour: "Navy",
      quantity: 1,
      notes: "",
    },
    {
      item: "Polo — Tactel",
      brand: "North Sails",
      fit: "male",
      size: "M",
      colour: "White",
      quantity: 1,
      notes: "",
    },
    {
      item: "Polo — Regatta (polyester)",
      brand: "North Sails",
      fit: "male",
      size: "M",
      colour: "White",
      quantity: 1,
      notes: "",
    },
    {
      item: "Polo — Regatta (polyester)",
      brand: "North Sails",
      fit: "male",
      size: "L",
      colour: "White",
      quantity: 1,
      notes: "",
    },
    {
      item: "Polo — Pique (cotton)",
      brand: "North Sails",
      fit: "male",
      size: "L",
      colour: "White",
      quantity: 1,
      notes: "",
    },
    {
      item: "Collared shirt (white)",
      brand: "Henbury",
      fit: "male",
      size: "M",
      colour: "White",
      quantity: 1,
      notes: "",
    },
    {
      item: "Polo — Pique (cotton)",
      brand: "North Sails",
      fit: "male",
      size: "XL",
      colour: "White",
      quantity: 1,
      notes: "",
    },
    {
      item: "Polo — Regatta (polyester)",
      brand: "North Sails",
      fit: "male",
      size: "XXL",
      colour: "Navy",
      quantity: 1,
      notes: "",
    },
    {
      item: "High Vis",
      brand: "Other",
      fit: "",
      size: "S-M",
      colour: "Yellow",
      quantity: 1,
      notes: "",
    },
  ];

  return rows.map((row, i) => ({
    ...row,
    image_url: "",
    id: `inv_seed_${i + 1}`,
    created_at: now,
    updated_at: now,
  }));
}
