import type { MockResource } from "./types"

/** Compact list for Marketing Home dashboard column. */
export const MARKETING_HOME_MOCK_RESOURCES: MockResource[] = [
  {
    id: "mh-res-1",
    title: "Q2 Campaign Playbook.pdf",
    category: "documents",
    fileType: "PDF",
    updatedAt: "3 days ago",
    addedAt: "3 days ago",
  },
  {
    id: "mh-res-2",
    title: "Brand Guidelines v2.1.pdf",
    category: "brand-guidelines",
    fileType: "PDF",
    updatedAt: "5 days ago",
    addedAt: "5 days ago",
  },
  {
    id: "mh-res-3",
    title: "Audience Personas.xlsx",
    category: "documents",
    fileType: "XLSX",
    updatedAt: "1 week ago",
    addedAt: "1 week ago",
  },
  {
    id: "mh-res-4",
    title: "Social Media Calendar.xlsx",
    category: "templates",
    fileType: "XLSX",
    updatedAt: "4 days ago",
    addedAt: "4 days ago",
  },
  {
    id: "mh-res-5",
    title: "Campaign Hero Image.jpg",
    category: "images",
    fileType: "JPG",
    updatedAt: "1 week ago",
    addedAt: "1 week ago",
  },
]

export const MOCK_RESOURCES: MockResource[] = [
  {
    id: "res-1",
    title: "PM_Logo_Primary_Colour.png",
    category: "logos",
    fileType: "PNG",
    description: "Logo — Primary Colour",
    fileSize: "284 KB",
    dimensions: "2000 × 1000 px",
    addedAt: "2 days ago",
    updatedAt: "2 days ago",
    usage: "For internal use only",
    tags: ["logo", "primary", "brand"],
    isInternalOnly: true,
    isFeatured: true,
    variantGroup: "pm-logo",
    owner: "Marketing Team",
  },
  {
    id: "res-2",
    title: "PM_Logo_Reversed.png",
    category: "logos",
    fileType: "PNG",
    description: "Logo — Reversed on dark backgrounds",
    fileSize: "276 KB",
    dimensions: "2000 × 1000 px",
    addedAt: "2 days ago",
    updatedAt: "2 days ago",
    usage: "For internal use only",
    tags: ["logo", "reversed"],
    isInternalOnly: true,
    variantGroup: "pm-logo",
    owner: "Marketing Team",
  },
  {
    id: "res-3",
    title: "PM_Logo_Monochrome.svg",
    category: "logos",
    fileType: "SVG",
    description: "Logo — Single colour",
    fileSize: "12 KB",
    addedAt: "1 week ago",
    updatedAt: "1 week ago",
    usage: "For internal use only",
    tags: ["logo", "monochrome"],
    variantGroup: "pm-logo",
  },
  {
    id: "res-4",
    title: "Brand_Guidelines_2026.pdf",
    category: "brand-guidelines",
    fileType: "PDF",
    description: "Official brand guidelines document",
    fileSize: "4.2 MB",
    addedAt: "5 days ago",
    updatedAt: "5 days ago",
    usage: "For internal use only",
    tags: ["guidelines", "brand", "2026"],
    isFeatured: true,
    owner: "Brand Team",
  },
  {
    id: "res-5",
    title: "Email_Signature_Guide.pdf",
    category: "brand-guidelines",
    fileType: "PDF",
    description: "Email signature setup guide",
    fileSize: "890 KB",
    addedAt: "2 weeks ago",
    updatedAt: "2 weeks ago",
    usage: "For internal use only",
    tags: ["email", "signature"],
  },
  {
    id: "res-6",
    title: "Campaign_Hero_01.jpg",
    category: "images",
    fileType: "JPG",
    description: "Campaign hero photography",
    fileSize: "1.8 MB",
    dimensions: "3840 × 2160 px",
    addedAt: "1 week ago",
    updatedAt: "1 week ago",
    usage: "Approved for internal campaigns",
    tags: ["campaign", "hero", "photography"],
    isFeatured: true,
  },
  {
    id: "res-7",
    title: "Boat_Show_Assets.zip",
    category: "images",
    fileType: "ZIP",
    description: "Boat show photography and graphics pack",
    fileSize: "128 MB",
    addedAt: "3 weeks ago",
    updatedAt: "3 weeks ago",
    tags: ["boat-show", "archive"],
  },
  {
    id: "res-8",
    title: "Social_Template_LinkedIn.pptx",
    category: "templates",
    fileType: "PPTX",
    description: "LinkedIn post template",
    fileSize: "2.1 MB",
    addedAt: "4 days ago",
    updatedAt: "4 days ago",
    usage: "For internal use only",
    tags: ["social", "linkedin", "template"],
  },
  {
    id: "res-9",
    title: "Internal_Presentation_Template.pptx",
    category: "templates",
    fileType: "PPTX",
    description: "Standard internal deck template",
    fileSize: "3.4 MB",
    addedAt: "1 month ago",
    updatedAt: "2 weeks ago",
    tags: ["presentation", "template"],
    owner: "Marketing Team",
  },
  {
    id: "res-10",
    title: "Q2_Campaign_Brief.docx",
    category: "documents",
    fileType: "DOCX",
    description: "Q2 campaign planning brief",
    fileSize: "540 KB",
    addedAt: "6 days ago",
    updatedAt: "6 days ago",
    tags: ["brief", "q2"],
  },
  {
    id: "res-11",
    title: "Product_Overview_Video.mp4",
    category: "videos",
    fileType: "MP4",
    description: "Product overview reel",
    fileSize: "45 MB",
    dimensions: "1920 × 1080",
    addedAt: "2 weeks ago",
    updatedAt: "2 weeks ago",
    tags: ["video", "product"],
  },
  {
    id: "res-12",
    title: "Annual_Review_Deck.pptx",
    category: "presentations",
    fileType: "PPTX",
    description: "Annual review presentation template",
    fileSize: "5.8 MB",
    addedAt: "10 days ago",
    updatedAt: "10 days ago",
    tags: ["presentation", "annual"],
    isFeatured: true,
  },
]
